openwrt:
  version: "22.03.5"
  target: x86-64
  model: generic
  baseurl: https://downloads.openwrt.org/releases
  sign:
    id: CD54E82DADB3684D
    fingerprint: BF856781A01293C8409ABE72CD54E82DADB3684D
    sha256sum: 0501809e242be14e154cf3bf47a9f9170765e5ad60c4f688ccfccb03388f2511
    baseurl: https://git.openwrt.org/?p=keyring.git;a=blob_plain;f=gpg
  disabled_services:
    - uhttpd
  defaults:
    # can be overwritten using pulumi:config("build").openwrt.defaults.ip
    ip: "192.168.1.1"
  packages:
    - coreutils-base64
    - coreutils-nohup
    - hostapd-utils
    - ipset
    - knot-dig
    - knot-host
    - knot-nsupdate
    - luci-app-firewall
    - luci-app-nlbwmon
    - luci-app-sqm
    - luci-app-unbound
    - luci-app-upnp
    - luci-app-wireguard
    - luci-app-wol
    - luci-mod-admin-full
    - luci-proto-ipv6
    - luci-proto-ppp
    - luci-proto-wireguard
    - luci-theme-material
    - mosquitto-client-ssl
    - qrencode
    - resolveip
    - tcpdump
    - unbound-anchor
    - unbound-control
    - unbound-control-setup
    - unbound-daemon
    # replaced packages
    - "-dropbear"
    - "-uhttpd"
    - "-wpad-basic-wolfssl"
    # remove nginx-ssl, dragged in by luci-ssl-nginx, because nginx-all-module conflicts with it
    - "-nginx-ssl"
    # replacement packages
    - nginx-all-module
    - luci-ssl-nginx
    - nginx-mod-luci-ssl
    - nginx-ssl-util
    - openssh-server
    - openssh-sftp-server
    - wpad-openssl

fcos:
  # Fedora-CoreOS
  stream: stable
  architecture: x86_64
  platform: metal
  format: raw.xz

raspberry:
  eeprom_rpi4:
    version: 2023.01.11-138c0
    fileurl: https://github.com/raspberrypi/rpi-eeprom/releases/download/v{VERSION}/rpi-boot-eeprom-recovery-2023-01-11-vl805-000138c0-sd.zip
    sha256sum: e53a915ada0e2e9eb3e995e8e50176eff4e1a2daea9d717d0f0aa30c5f9fd04d
  uboot:
    version: 2023.04-1.fc38
    fileurl: https://kojipkgs.fedoraproject.org//packages/uboot-tools/2023.04/1.fc38/noarch/uboot-images-armv8-{VERSION}.noarch.rpm
    sha256sum: f5288755b42abd9dd546ddae8bb7aed33e6a5e4a19f98c2f0535ac66cf1220a2
  uefi_rpi3:
    version: "1.39"
    fileurl: https://github.com/pftf/RPi3/releases/download/v{VERSION}/RPi3_UEFI_Firmware_v{VERSION}.zip
    sha256sum: 9d2bae7868027997c59663d2a29c5a5573c4a846d67d0cd42cdddb5280ee22d8
  uefi_rpi4:
    version: "1.35"
    fileurl: https://github.com/pftf/RPi4/releases/download/v{VERSION}/RPi4_UEFI_Firmware_v{VERSION}.zip
    sha256sum: 3ea16d6bc4f8f122527ad6a84c0fe84ad80d85fd43a868d99c360ad9e93d3f6e

homeassistant:
  version: "10.2"
  baseurl: https://github.com/home-assistant/operating-system/releases/download
  target: generic-x86-64

esphome:
  esp32:
    board: adafruit_feather_esp32_v2
    framework:
      type: esp-idf
      # version:
      # platform_version:
      sdkconfig_options:
        # CONFIG_MBEDTLS_DEBUG: y

truenas:
  version: "13.0"
  patchlevel: U5.1
  baseurl: https://download.freenas.org
  sign:
    id: C8D62DEF767C1DB0DFF4E6EC358EAA9112CF7946
    keyfile: salt://build/truenas.asc

android:
  - type: mobile_phone
    packages:
      []
      # fdroid repositories and packages
  - type: wifi_tablet
  - type: wifi_phone
  - type: wifi_appliance
